import {
  User,
  Link,
  Phone,
  Instagram,
  Twitter,
  Linkedin,
  Github,
  Youtube,
  Music,
  ImageIcon,
  Video,
  FileText,
  Globe,
  Calendar,
  Star,
  Mail,
  Clock,
  MapPin,
  GraduationCap,
  Briefcase,
  FolderOpen,
  Code,
  MessageSquare,
  Facebook,
  MessageCircle,
} from "lucide-react"

export const BLOCK_TYPES = {
  about: {
    name: "About",
    description: "Tell your story",
    icon: <User className="h-4 w-4" />,
    fields: [
      { key: "content", label: "About Text", type: "textarea", placeholder: "Tell people about yourself..." },
      { key: "descriptionType", label: "Description Format", type: "select", options: ["plain", "markdown"] },
    ],
  },
  education: {
    name: "Education",
    description: "Show your educational background",
    icon: <GraduationCap className="h-4 w-4" />,
    fields: [{ key: "entries", label: "Education Entries", type: "timeline-entries" }],
  },
  experience: {
    name: "Experience",
    description: "Display your work experience",
    icon: <Briefcase className="h-4 w-4" />,
    fields: [{ key: "entries", label: "Experience Entries", type: "timeline-entries" }],
  },
  project: {
    name: "Projects",
    description: "Showcase your projects with files and links",
    icon: <FolderOpen className="h-4 w-4" />,
    fields: [{ key: "project-entries", label: "Project Entries", type: "project-entries" }],
  },
  achievement: {
    name: "Achievements",
    description: "Showcase your accomplishments and awards",
    icon: <Star className="h-4 w-4" />,
    fields: [
      { key: "entries", label: "Achievement Entries", type: "achievement-entries" },
      { key: "displayStyle", label: "Display Style", type: "select", options: ["zigzag", "cards"] },
    ],
  },
  skill: {
    name: "Skills",
    description: "Display your technical skills with proficiency levels",
    icon: <Code className="h-4 w-4" />,
    fields: [{ key: "entries", label: "Skill Entries", type: "skill-entries" }],
  },
  social: {
    name: "Social Media",
    description: "Link your social profiles",
    icon: <Link className="h-4 w-4" />,
    fields: [
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: ["discord", "facebook", "github", "instagram", "linkedin", "tiktok", "twitter", "whatsapp", "youtube"],
      },
      { key: "username", label: "Username", type: "text", placeholder: "@username" },
      { key: "url", label: "Profile URL", type: "url", placeholder: "https://..." },
    ],
  },
  services: {
    name: "Services",
    description: "Showcase your services with optional photos",
    icon: <Briefcase className="h-4 w-4" />,
    fields: [{ key: "entries", label: "Service Entries", type: "service-entries" }],
  },
  whatsapp: {
    name: "WhatsApp",
    description: "Add a WhatsApp contact button",
    icon: <MessageSquare className="h-4 w-4" />,
    fields: [
      { key: "phoneNumber", label: "Phone Number", type: "text", placeholder: "+1234567890" },
      { key: "message", label: "Pre-filled Message", type: "textarea", placeholder: "Hello, I'd like to connect with you!" },
      { key: "buttonText", label: "Button Text", type: "text", placeholder: "Chat on WhatsApp" },
      { key: "description", label: "Description", type: "text", placeholder: "Contact me on WhatsApp for quick responses" },
    ],
  },
  contact: {
    name: "Contact",
    description: "Share contact information or add a contact form",
    icon: <Phone className="h-4 w-4" />,
    fields: [
      { key: "mode", label: "Contact Mode", type: "select", options: ["display", "form"] },
      // Display mode fields
      {
        key: "type",
        label: "Contact Type",
        type: "select",
        options: ["email", "phone", "address", "website"],
        conditional: { field: "mode", value: "display" },
      },
      {
        key: "label",
        label: "Label",
        type: "text",
        placeholder: "Work Email",
        conditional: { field: "mode", value: "display" },
      },
      {
        key: "value",
        label: "Value",
        type: "text",
        placeholder: "contact@example.com",
        conditional: { field: "mode", value: "display" },
      },
      // Form mode fields
      {
        key: "formTitle",
        label: "Form Title",
        type: "text",
        placeholder: "Get in Touch",
        conditional: { field: "mode", value: "form" },
      },
      {
        key: "formDescription",
        label: "Form Description",
        type: "textarea",
        placeholder: "Send me a message and I'll get back to you soon.",
        conditional: { field: "mode", value: "form" },
      },
      {
        key: "notificationEmail",
        label: "Notification Email",
        type: "email",
        placeholder: "your@email.com (defaults to account email)",
        conditional: { field: "mode", value: "form" },
      },
      {
        key: "successMessage",
        label: "Success Message",
        type: "text",
        placeholder: "Thanks for your message! I'll get back to you soon.",
        conditional: { field: "mode", value: "form" },
      },
    ],
  },
  subscription: {
    name: "Email Subscription",
    description: "Collect email subscribers",
    icon: <Mail className="h-4 w-4" />,
    fields: [
      { key: "title", label: "Title", type: "text", placeholder: "Subscribe to my newsletter" },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Get updates about my latest work...",
      },
      { key: "buttonText", label: "Button Text", type: "text", placeholder: "Subscribe" },
      { key: "successMessage", label: "Success Message", type: "text", placeholder: "Thanks for subscribing!" },
      { key: "collectName", label: "Collect Name", type: "select", options: ["yes", "no"] },
    ],
  },
  link: {
    name: "Link",
    description: "Add important links",
    icon: <Globe className="h-4 w-4" />,
    fields: [
      { key: "title", label: "Link Title", type: "text", placeholder: "My Portfolio" },
      { key: "url", label: "URL", type: "url", placeholder: "https://..." },
      { key: "description", label: "Description", type: "text", placeholder: "Optional description" },
    ],
  },
  gallery: {
    name: "Gallery",
    description: "Showcase your work",
    icon: <ImageIcon className="h-4 w-4" />,
    fields: [
      { key: "title", label: "Gallery Title", type: "text", placeholder: "My Work" },
      { key: "description", label: "Description", type: "textarea", placeholder: "Describe your gallery..." },
      { key: "images", label: "Images", type: "image-array", accept: "image/*", multiple: true },
    ],
  },
  video: {
    name: "Video",
    description: "Embed videos",
    icon: <Video className="h-4 w-4" />,
    fields: [
      { key: "title", label: "Video Title", type: "text", placeholder: "My Video" },
      { key: "url", label: "Video URL", type: "url", placeholder: "YouTube, Vimeo, or direct video URL" },
      { key: "description", label: "Description", type: "textarea", placeholder: "Describe your video..." },
    ],
  },
  audio: {
    name: "Audio",
    description: "Share audio content",
    icon: <Music className="h-4 w-4" />,
    fields: [
      { key: "title", label: "Audio Title", type: "text", placeholder: "My Podcast" },
      { key: "url", label: "Audio URL", type: "url", placeholder: "Spotify, SoundCloud, or direct audio URL" },
      { key: "description", label: "Description", type: "textarea", placeholder: "Describe your audio..." },
    ],
  },
  text: {
    name: "Text Block",
    description: "Add formatted text",
    icon: <FileText className="h-4 w-4" />,
    fields: [
      { key: "title", label: "Title", type: "text", placeholder: "Section Title" },
      { key: "content", label: "Content", type: "textarea", placeholder: "Your text content..." },
      { key: "descriptionType", label: "Content Format", type: "select", options: ["plain", "markdown"] },
    ],
  },
  testimonial: {
    name: "Testimonial",
    description: "Share client feedback",
    icon: <Star className="h-4 w-4" />,
    fields: [
      { key: "quote", label: "Quote", type: "textarea", placeholder: "The testimonial text..." },
      { key: "descriptionType", label: "Quote Format", type: "select", options: ["plain", "markdown"] },
      { key: "author", label: "Author", type: "text", placeholder: "Client Name" },
      { key: "position", label: "Position", type: "text", placeholder: "CEO at Company" },
      { key: "avatar", label: "Avatar URL", type: "url", placeholder: "https://..." },
    ],
  },
  event: {
    name: "Event",
    description: "Promote upcoming events",
    icon: <Calendar className="h-4 w-4" />,
    fields: [
      { key: "title", label: "Event Title", type: "text", placeholder: "My Workshop" },
      { key: "date", label: "Date", type: "date" },
      { key: "time", label: "Time", type: "time" },
      { key: "location", label: "Location", type: "text", placeholder: "Online or venue" },
      { key: "description", label: "Description", type: "textarea", placeholder: "Event details..." },
      { key: "descriptionType", label: "Description Format", type: "select", options: ["plain", "markdown"] },
      { key: "link", label: "Registration Link", type: "url", placeholder: "https://..." },
    ],
  },
  timezone: {
    name: "Timezone Clock",
    description: "Display live time for any timezone",
    icon: <Clock className="h-4 w-4" />,
    fields: [
      {
        key: "timezone",
        label: "Timezone",
        type: "select",
        options: [
          "America/New_York",
          "America/Los_Angeles",
          "America/Chicago",
          "Europe/London",
          "Europe/Paris",
          "Europe/Berlin",
          "Asia/Tokyo",
          "Asia/Shanghai",
          "Asia/Kolkata",
          "Asia/Dubai",
          "Asia/Dhaka",
          "Australia/Sydney",
          "Pacific/Auckland",
          "UTC",
        ],
      },
      {
        key: "format",
        label: "Time Format",
        type: "select",
        options: ["12", "24"],
      },
      {
        key: "showDate",
        label: "Show Date",
        type: "select",
        options: ["yes", "no"],
      },
      {
        key: "showSeconds",
        label: "Show Seconds",
        type: "select",
        options: ["yes", "no"],
      },
      {
        key: "customLabel",
        label: "Custom Label",
        type: "text",
        placeholder: "My Local Time",
      },
    ],
  },
  location: {
    name: "Location",
    description: "Share your location",
    icon: <MapPin className="h-4 w-4" />,
    fields: [
      { key: "address", label: "Address", type: "text", placeholder: "123 Main Street" },
      { key: "city", label: "City", type: "text", placeholder: "New York" },
      { key: "country", label: "Country", type: "text", placeholder: "United States" },
    ],
  },
  calendar: {
    name: "Calendar",
    description: "Mark important dates",
    icon: <Calendar className="h-4 w-4" />,
    fields: [
      { key: "title", label: "Event Title", type: "text", placeholder: "Important Date" },
      { key: "date", label: "Start Date", type: "date" },
      { key: "endDate", label: "End Date (Optional)", type: "date" },
      { key: "description", label: "Description", type: "textarea", placeholder: "Event description..." },
    ],
  },
  image: {
    name: "Image",
    description: "Upload and display images",
    icon: <ImageIcon className="h-4 w-4" />,
    fields: [
      { key: "imageUrl", label: "Image URL", type: "url", placeholder: "https://example.com/image.jpg" },
      { key: "size", label: "Size", type: "select", options: ["small", "medium", "large", "full"] },
    ],
  },
}

export const SOCIAL_PLATFORMS = {
  discord: {
    name: "Discord",
    icon: <MessageCircle className="h-4 w-4" />,
    color: "bg-indigo-600",
    baseUrl: "https://discord.com/users/",
  },
  facebook: {
    name: "Facebook",
    icon: <Facebook className="h-4 w-4" />,
    color: "bg-blue-600",
    baseUrl: "https://facebook.com/",
  },
  github: {
    name: "GitHub",
    icon: <Github className="h-4 w-4" />,
    color: "bg-gray-800",
    baseUrl: "https://github.com/",
  },
  instagram: {
    name: "Instagram",
    icon: <Instagram className="h-4 w-4" />,
    color: "bg-pink-500",
    baseUrl: "https://instagram.com/",
  },
  linkedin: {
    name: "LinkedIn",
    icon: <Linkedin className="h-4 w-4" />,
    color: "bg-blue-700",
    baseUrl: "https://linkedin.com/in/",
  },
  tiktok: {
    name: "TikTok",
    icon: <Music className="h-4 w-4" />,
    color: "bg-black",
    baseUrl: "https://tiktok.com/@",
  },
  twitter: {
    name: "Twitter",
    icon: <Twitter className="h-4 w-4" />,
    color: "bg-blue-500",
    baseUrl: "https://twitter.com/",
  },
  whatsapp: {
    name: "WhatsApp",
    icon: <MessageSquare className="h-4 w-4" />,
    color: "bg-green-500",
    baseUrl: "https://wa.me/",
  },
  youtube: {
    name: "YouTube",
    icon: <Youtube className="h-4 w-4" />,
    color: "bg-red-500",
    baseUrl: "https://youtube.com/@",
  },
}
